In [8]:
import pandas as pd

data = pd.read_csv('./data/Dataset_feuilles_1.csv')
data.head()

,id,species,margin1,margin2,margin3,margin4,margin5,margin6,margin7,margin8,...,texture55,texture56,texture57,texture58,texture59,texture60,texture61,texture62,texture63,texture64
0,1,Acer_Opalus,0.007812,0.023438,0.023438,0.003906,0.011719,0.009766,0.027344,0.0,...,0.007812,0.000000,0.002930,0.002930,0.035156,0.0,0.0,0.004883,0.000000,0.025391
1,2,Pterocarya_Stenoptera,0.005859,0.000000,0.031250,0.015625,0.025391,0.001953,0.019531,0.0,...,0.000977,0.000000,0.000000,0.000977,0.023438,0.0,0.0,0.000977,0.039062,0.022461
2,3,Quercus_Hartwissiana,0.005859,0.009766,0.019531,0.007812,0.003906,0.005859,0.068359,0.0,...,0.154300,0.000000,0.005859,0.000977,0.007812,0.0,0.0,0.000000,0.020508,0.002930
3,5,Tilia_Tomentosa,0.000000,0.003906,0.023438,0.005859,0.021484,0.019531,0.023438,0.0,...,0.000000,0.000977,0.000000,0.000000,0.020508,0.0,0.0,0.017578,0.000000,0.047852
4,6,Quercus_Variabilis,0.005859,0.003906,0.048828,0.009766,0.013672,0.015625,0.005859,0.0,...,0.096680,0.000000,0.021484,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.031250

In [9]:
test = pd.read_csv('./data/test.csv')
test.head()

,id,margin1,margin2,margin3,margin4,margin5,margin6,margin7,margin8,margin9,...,texture55,texture56,texture57,texture58,texture59,texture60,texture61,texture62,texture63,texture64
0,4,0.019531,0.009766,0.078125,0.011719,0.003906,0.015625,0.005859,0.0,0.005859,...,0.006836,0.000000,0.015625,0.000977,0.015625,0.0,0.0,0.000000,0.003906,0.053711
1,7,0.007812,0.005859,0.064453,0.009766,0.003906,0.013672,0.007812,0.0,0.033203,...,0.000000,0.000000,0.006836,0.001953,0.013672,0.0,0.0,0.000977,0.037109,0.044922
2,9,0.000000,0.000000,0.001953,0.021484,0.041016,0.000000,0.023438,0.0,0.011719,...,0.128910,0.000000,0.000977,0.000000,0.000000,0.0,0.0,0.015625,0.000000,0.000000
3,12,0.000000,0.000000,0.009766,0.011719,0.017578,0.000000,0.003906,0.0,0.003906,...,0.012695,0.015625,0.002930,0.036133,0.013672,0.0,0.0,0.089844,0.000000,0.008789
4,13,0.001953,0.000000,0.015625,0.009766,0.039062,0.000000,0.009766,0.0,0.005859,...,0.000000,0.042969,0.016602,0.010742,0.041016,0.0,0.0,0.007812,0.009766,0.007812

In [10]:
X = data.iloc[:, 2:]
y = data.iloc[:,1]

In [11]:
y

0                Acer_Opalus
1      Pterocarya_Stenoptera
2       Quercus_Hartwissiana
3            Tilia_Tomentosa
4         Quercus_Variabilis
               ...
985     Magnolia_Salicifolia
986              Acer_Pictum
987       Alnus_Maximowiczii
988            Quercus_Rubra
989           Quercus_Afares
Name: species, Length: 990, dtype: object

In [12]:
from sklearn import preprocessing
scaler = preprocessing.StandardScaler()
scaler.fit(X)
X_scaled = scaler.transform(X)

In [13]:
pd.DataFrame(X_scaled).describe().round(2)

,0,1,2,3,4,5,6,7,8,9,...,182,183,184,185,186,187,188,189,190,191
count,990.00,990.00,990.00,990.00,990.00,990.00,990.00,990.0,990.00,990.00,...,990.00,990.00,990.00,990.00,990.00,990.00,990.00,990.00,990.00,990.00
mean,-0.00,0.00,-0.00,-0.00,0.00,0.00,-0.00,0.0,0.00,0.00,...,-0.00,0.00,-0.00,0.00,-0.00,0.00,0.00,-0.00,0.00,-0.00
std,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.0,1.00,1.00,...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
min,-0.88,-0.73,-1.24,-0.82,-0.78,-0.74,-1.10,-0.4,-0.80,-1.16,...,-0.58,-0.26,-0.69,-0.46,-1.05,-0.23,-0.24,-0.52,-0.65,-0.85
25%,-0.78,-0.68,-0.71,-0.61,-0.67,-0.74,-0.76,-0.4,-0.58,-0.80,...,-0.58,-0.26,-0.65,-0.46,-0.73,-0.23,-0.24,-0.52,-0.65,-0.81
50%,-0.39,-0.43,-0.26,-0.34,-0.35,-0.44,-0.20,-0.4,-0.15,-0.19,...,-0.50,-0.26,-0.43,-0.42,-0.22,-0.23,-0.24,-0.42,-0.44,-0.34
75%,0.40,0.32,0.50,0.21,0.18,0.34,0.58,-0.4,0.07,0.54,...,0.11,-0.26,0.27,-0.07,0.35,-0.23,-0.24,0.08,0.27,0.43
max,3.57,4.55,4.81,5.16,5.28,5.23,4.15,11.0,7.73,4.92,...,6.20,10.21,6.76,7.54,5.89,9.38,13.03,9.12,5.65,5.37

In [14]:
encoder = preprocessing.LabelEncoder()
y = encoder.fit_transform(y)

In [15]:
from sklearn import model_selection
X_train, X_test, y_train, y_test = model_selection.train_test_split(X_scaled, y, test_size=0.3, random_state=42)

In [16]:
from sklearn import neighbors

estimator = neighbors.KNeighborsClassifier(n_jobs=-1)

estimator.fit(X_train, y_train)

KNeighborsClassifier(n_jobs=-1)

In [20]:
import numpy as np
baseline_accuracy = estimator.score(X=X_test, y=y_test)
baseline_accuracy

0.9461279461279462

In [33]:
from sklearn import multiclass
from sklearn.svm import LinearSVC
from sklearn import model_selection

estimator = multiclass.OneVsOneClassifier(n_jobs=-1, estimator=LinearSVC(random_state=40))

params = {'estimator__penalty': ['l1','l2'], 'estimator__C': np.logspace(-3,3,7)}

grid = model_selection.GridSearchCV(estimator=estimator, param_grid=params, n_jobs=-1, cv=3, return_train_score=True, verbose=True, scoring='accuracy')

grid.fit(X_train, y_train)

best_score = grid.best_score_
best_score

Fitting 3 folds for each of 14 candidates, totalling 42 fits

C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning:
21 fits failed out of a total of 42.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
21 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\sklearn\multiclass.py", line 690, in fit
    Parallel(n_jobs=self.n_jobs)(
  File "C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\sklearn\utils\parallel.py", line 63, in __call__
    return super().__call__(iterable_with_config)
  File "C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\joblib\parallel.py", line 1098, in __call__
    self.retrieve()
  File "C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\joblib\parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\Users\Papoun\anaconda3\envs\oc-p4\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Users\Papoun\anaconda3\envs\oc-p4\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\joblib\_parallel_backends.py", line 620, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\joblib\parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\joblib\parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\sklearn\utils\parallel.py", line 123, in __call__
    return self.function(*args, **kwargs)
  File "C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\sklearn\multiclass.py", line 549, in _fit_ovo_binary
    _fit_binary(
  File "C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\sklearn\multiclass.py", line 83, in _fit_binary
    estimator.fit(X, y)
  File "C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\sklearn\svm\_classes.py", line 274, in fit
    self.coef_, self.intercept_, n_iter_ = _fit_liblinear(
  File "C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\sklearn\svm\_base.py", line 1223, in _fit_liblinear
    solver_type = _get_liblinear_solver_type(multi_class, penalty, loss, dual)
  File "C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\sklearn\svm\_base.py", line 1062, in _get_liblinear_solver_type
    raise ValueError(
ValueError: Unsupported set of arguments: The combination of penalty='l1' and loss='squared_hinge' are not supported when dual=True, Parameters: penalty='l1', loss='squared_hinge', dual=True

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\sklearn\model_selection\_search.py:952: UserWarning: One or more of the test scores are non-finite: [       nan 0.91919192        nan 0.97546898        nan 0.97402597
        nan 0.97546898        nan 0.97546898        nan 0.97546898
        nan 0.97546898]
  warnings.warn(
C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\sklearn\model_selection\_search.py:952: UserWarning: One or more of the train scores are non-finite: [       nan 0.98629149        nan 1.                nan 1.
        nan 1.                nan 1.                nan 1.
        nan 1.        ]
  warnings.warn(

0.9754689754689755

In [34]:
grid.best_params_

{'estimator__C': 0.01, 'estimator__penalty': 'l2'}

In [35]:
estimator = multiclass.OneVsOneClassifier(n_jobs=-1, estimator=LinearSVC(penalty='l2', C=0.01))

estimator.fit(X_train, y_train)
score = estimator.score(X_test, y_test)
score

0.98989898989899

In [36]:
estimator = multiclass.OneVsRestClassifier(n_jobs=-1, estimator=LinearSVC(random_state=40))

params = {'estimator__penalty': ['l1','l2'], 'estimator__C': np.logspace(-3,3,7)}

grid = model_selection.GridSearchCV(estimator=estimator, param_grid=params, n_jobs=-1, cv=3, return_train_score=True, verbose=True, scoring='accuracy')

grid.fit(X_train, y_train)

best_score = grid.best_score_
best_score

Fitting 3 folds for each of 14 candidates, totalling 42 fits

C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning:
21 fits failed out of a total of 42.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
21 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\sklearn\multiclass.py", line 330, in fit
    self.estimators_ = Parallel(n_jobs=self.n_jobs, verbose=self.verbose)(
  File "C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\sklearn\utils\parallel.py", line 63, in __call__
    return super().__call__(iterable_with_config)
  File "C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\joblib\parallel.py", line 1098, in __call__
    self.retrieve()
  File "C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\joblib\parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\Users\Papoun\anaconda3\envs\oc-p4\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Users\Papoun\anaconda3\envs\oc-p4\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\joblib\_parallel_backends.py", line 620, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\joblib\parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\joblib\parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\sklearn\utils\parallel.py", line 123, in __call__
    return self.function(*args, **kwargs)
  File "C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\sklearn\multiclass.py", line 83, in _fit_binary
    estimator.fit(X, y)
  File "C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\sklearn\svm\_classes.py", line 274, in fit
    self.coef_, self.intercept_, n_iter_ = _fit_liblinear(
  File "C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\sklearn\svm\_base.py", line 1223, in _fit_liblinear
    solver_type = _get_liblinear_solver_type(multi_class, penalty, loss, dual)
  File "C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\sklearn\svm\_base.py", line 1062, in _get_liblinear_solver_type
    raise ValueError(
ValueError: Unsupported set of arguments: The combination of penalty='l1' and loss='squared_hinge' are not supported when dual=True, Parameters: penalty='l1', loss='squared_hinge', dual=True

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\sklearn\model_selection\_search.py:952: UserWarning: One or more of the test scores are non-finite: [       nan 0.87301587        nan 0.89466089        nan 0.91919192
        nan 0.90909091        nan 0.90620491        nan 0.90620491
        nan 0.90620491]
  warnings.warn(
C:\Users\Papoun\anaconda3\envs\oc-p4\lib\site-packages\sklearn\model_selection\_search.py:952: UserWarning: One or more of the train scores are non-finite: [       nan 0.97330447        nan 0.9978355         nan 1.
        nan 1.                nan 1.                nan 1.
        nan 1.        ]
  warnings.warn(

0.9191919191919191

In [37]:
grid.best_params_

{'estimator__C': 0.1, 'estimator__penalty': 'l2'}

In [39]:
estimator = multiclass.OneVsRestClassifier(n_jobs=-1, estimator=LinearSVC(penalty='l2', C=0.01, random_state=40))

estimator.fit(X_train, y_train)
score = estimator.score(X_test, y_test)
score

0.8855218855218855