# Imports

In [167]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn import preprocessing

import time
from contextlib import contextmanager
import gc
import warnings
import pprint
from IPython.display import clear_output

# Configuration

In [168]:
DEBUG = True
DF_MAIN = None
TEST_SIZE = 1/4
SAMPLE_ROWS = 10000
RANDOM_STATE= 190276
ROOT_INPUT = './data/original/'

warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.simplefilter(action='ignore', category=UserWarning)
sns.set()

# Fonctions

In [169]:
# Time tracking
@contextmanager
def timer(title: str):
    t0 = time.time()
    yield
    print("{} - éxécuté en {:.0f}s".format(title, time.time() - t0))

# Read and Sample CSV
def read(name: str, index: str = None, dates: [str] = []) -> pd.DataFrame:
    path = ROOT_INPUT + name
    print(f"Read file {path}")
    df = pd.read_csv(ROOT_INPUT + name, index_col=index, parse_dates= dates)
    print(f'{name} shape: {df.shape}')
    return df

# Affichage des infos du dataset
def infos(df: pd.DataFrame, head = False):
    memory_gb = np.round(df.memory_usage(deep=True).sum()/(1024**3),2)
    nb_lignes = df.shape[0]
    nb_columns = df.shape[1]
    print(f'A ce stade ce dataset contient {nb_lignes} lignes et {nb_columns} colonnes. (conso mémoire {memory_gb}Gb)')
    if head:
        return df.head()
    
# Graphe des taux de remplissage
def remplissage(df: pd.DataFrame, treshold: int = 101, ascending: bool = False):
    df_na = pd.DataFrame(((1- df.isna().mean()) * 100).round(0)).rename(columns={0: 'mean'})
    df_na = df_na[df_na['mean'] < treshold]
    ax = sns.barplot(data=df_na, x='mean', y=df_na.index, palette='rainbow', order=df_na.sort_values(by='mean', ascending=ascending).index)
    ax.bar_label(ax.containers[0], fmt='%.0f%%', padding=-35, c="white")
    plt.title(f'Taux de remplissage inférieur à {treshold} : {df_na.size} colonnes')
    plt.show()
    
def split(df: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    df_train, df_test = model_selection.train_test_split(df, test_size=TEST_SIZE, random_state= RANDOM_STATE)
    return df_train, df_test

def scale(df: pd.DataFrame) -> pd.DataFrame:
    scaler = preprocessing.StandardScaler()
    columns = df.columns
    index = df.index
    df_scaled = scaler.fit_transform(df)
    
    df_scaled = pd.DataFrame(df_scaled, columns=columns, index=index)
    
    return df_scaled

def one_hot_encode(df: pd.DataFrame) -> tuple[pd.DataFrame, [str]]:
    print(f"shape before encode: {df.shape}")    
    
    previous_columns = df.columns.to_list()
    df = pd.get_dummies(df)
    after_columns = df.columns.to_list()
    cols = [col for index, col in enumerate(after_columns) if col not in previous_columns]
        
    print(f"shape after encode: {df.shape}")
       
    return df, cols

# Load DataFrames

In [170]:
df_infos = [
    {'file': 'olist_customers_dataset.csv', 'index': 'customer_id', 'name': 'customers', 'dates': []},
    {'file': 'olist_geolocation_dataset.csv', 'index': 'geolocation_zip_code_prefix', 'name': 'geolocation', 'dates': []},
    {'file': 'olist_order_items_dataset.csv', 'index': 'order_id', 'name': 'order_items', 'dates': ['shipping_limit_date']},
    {'file': 'olist_order_payments_dataset.csv', 'index': 'order_id', 'name': 'order_payments', 'dates': []},
    {'file': 'olist_order_reviews_dataset.csv', 'index': 'review_id', 'name': 'order_reviews', 'dates': ['review_creation_date', 'review_answer_timestamp']},
    {'file': 'olist_orders_dataset.csv', 'index': 'order_id', 'name': 'orders', 'dates': ['order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']},
    {'file': 'olist_products_dataset.csv', 'index': 'product_id', 'name': 'products', 'dates': []},
    {'file': 'olist_sellers_dataset.csv', 'index': 'seller_id', 'name': 'sellers', 'dates': []},
    {'file': 'product_category_name_translation.csv', 'index': 'product_category_name', 'name': 'product_category_name_translation', 'dates': []}
]

dfs: dict[str, pd.DataFrame] = {}

for info in df_infos:
    dfs[info['name']] = read(name=info['file'], index=info['index'], dates=info['dates'])
    print("")


# Copy originals dataFrames
df_customers = dfs['customers'].copy()
df_geolocation = dfs['geolocation'].copy()
df_order_items = dfs['order_items'].copy()
df_order_payments = dfs['order_payments'].copy()
df_order_reviews = dfs['order_reviews'].copy()
df_orders = dfs['orders'].copy()
df_products = dfs['products'].copy()
df_sellers = dfs['sellers'].copy()
df_product_category_name_translation = dfs['product_category_name_translation']


print('Les dataframes suivants sont chargés:')
pprint.pprint(list(dfs.keys()))

Read file ./data/original/olist_customers_dataset.csv
olist_customers_dataset.csv shape: (99441, 4)

Read file ./data/original/olist_geolocation_dataset.csv
olist_geolocation_dataset.csv shape: (1000163, 4)

Read file ./data/original/olist_order_items_dataset.csv
olist_order_items_dataset.csv shape: (112650, 6)

Read file ./data/original/olist_order_payments_dataset.csv
olist_order_payments_dataset.csv shape: (103886, 4)

Read file ./data/original/olist_order_reviews_dataset.csv
olist_order_reviews_dataset.csv shape: (99224, 6)

Read file ./data/original/olist_orders_dataset.csv
olist_orders_dataset.csv shape: (99441, 7)

Read file ./data/original/olist_products_dataset.csv
olist_products_dataset.csv shape: (32951, 8)

Read file ./data/original/olist_sellers_dataset.csv
olist_sellers_dataset.csv shape: (3095, 3)

Read file ./data/original/product_category_name_translation.csv
product_category_name_translation.csv shape: (71, 1)

Les dataframes suivants sont chargés:
['customers',
 'geolocation',
 'order_items',
 'order_payments',
 'order_reviews',
 'orders',
 'products',
 'sellers',
 'product_category_name_translation']

# Aggregate DataFrames

## Aggregation de Geolocation dans Sellers et Customers

In [171]:
df_geolocation.head()

,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
geolocation_zip_code_prefix,,,,
1037,-23.545621,-46.639292,sao paulo,SP
1046,-23.546081,-46.644820,sao paulo,SP
1046,-23.546129,-46.642951,sao paulo,SP
1041,-23.544392,-46.639499,sao paulo,SP
1035,-23.541578,-46.641607,sao paulo,SP

In [172]:
df_geolocation.index.has_duplicates

True

Les zip codes apparaissent plusieurs fois avec des données GPS différentes => Groupement par Zip code avec median des Longitude/Latitude avant aggrégation à Customers et Sellers

In [173]:
df_geolocation = df_geolocation.groupby('geolocation_zip_code_prefix').agg({'geolocation_lat': 'median', 'geolocation_lng': 'median'})
df_geolocation.head()

                             geolocation_lat  geolocation_lng
geolocation_zip_code_prefix
1001                              -23.550381       -46.634027
1002                              -23.548551       -46.635072
1003                              -23.548977       -46.635313
1004                              -23.549535       -46.634771
1005                              -23.549612       -46.636532

Ajout de Geolocation à Customers et Sellers.

In [174]:
df_customers = df_customers.join(df_geolocation, on='customer_zip_code_prefix')
df_customers.rename(columns={'geolocation_lat': 'customer_geolocation_lat'}, inplace=True)
df_customers.rename(columns={'geolocation_lng': 'customer_geolocation_lng'}, inplace=True)

df_sellers = df_sellers.join(df_geolocation, on='seller_zip_code_prefix')
df_sellers.rename(columns={'geolocation_lat': 'seller_geolocation_lat'}, inplace=True)
df_sellers.rename(columns={'geolocation_lng': 'seller_geolocation_lng'}, inplace=True)

## Aggrégation de Customers, Order_reviews, Order_payments dans Orders

### Traitement Customers

In [175]:
df_customers.head()

,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,customer_geolocation_lat,customer_geolocation_lng
customer_id,,,,,,
06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,-20.502070,-47.396822
18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,-23.727299,-46.542631
4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,-23.531294,-46.656404
b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,-23.497390,-46.182342
4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,-22.973309,-47.141530

In [176]:
df_customers.index.has_duplicates

False

Pas de traitement nécéssaire avant aggrégation dans Orders

### Traitement Order_payments

In [177]:
df_order_payments.head()

,payment_sequential,payment_type,payment_installments,payment_value
order_id,,,,
b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [178]:
df_order_payments.index.has_duplicates

True

Traitement nécéssaire pour aggreger Order_payments dans Orders:
1. Encoder payment_type
2. Grouper par order_id

In [179]:
df_order_payments = pd.get_dummies(df_order_payments, columns=['payment_type'], dtype=int)

In [180]:
df_order_payments

,payment_sequential,payment_installments,payment_value,payment_type_boleto,payment_type_credit_card,payment_type_debit_card,payment_type_not_defined,payment_type_voucher
order_id,,,,,,,,
b81ef226f3fe1789b1e8b2acac839d17,1,8,99.33,0,1,0,0,0
a9810da82917af2d9aefd1278f1dcfa0,1,1,24.39,0,1,0,0,0
25e8ea4e93396b6fa0d3dd708e76c1bd,1,1,65.71,0,1,0,0,0
ba78997921bbcdc1373bb41e913ab953,1,8,107.78,0,1,0,0,0
42fdf880ba16b47b59251dd489d4441a,1,2,128.45,0,1,0,0,0
...,...,...,...,...,...,...,...,...
0406037ad97740d563a178ecc7a2075c,1,1,363.31,1,0,0,0,0
7b905861d7c825891d6347454ea7863f,1,2,96.80,0,1,0,0,0
32609bbb3dd69b3c066a6860554a77bf,1,1,47.77,0,1,0,0,0
b8b61059626efa996a60be9bb9320e10,1,5,369.54,0,1,0,0,0
28bbae6599b09d39ca406b747b6632b1,1,1,191.58,1,0,0,0,0

In [181]:
agg = {
    'payment_sequential': 'max',
    'payment_installments': 'max',
    'payment_value': 'sum',
    'payment_type_boleto': 'max',
    'payment_type_credit_card': 'max',
    'payment_type_debit_card': 'max',
    'payment_type_not_defined': 'max',
    'payment_type_voucher': 'max'
}
df_order_payments = df_order_payments.groupby('order_id').agg(agg)

In [182]:
df_order_payments

,payment_sequential,payment_installments,payment_value,payment_type_boleto,payment_type_credit_card,payment_type_debit_card,payment_type_not_defined,payment_type_voucher
order_id,,,,,,,,
00010242fe8c5a6d1ba2dd792cb16214,1,2,72.19,0,1,0,0,0
00018f77f2f0320c557190d7a144bdd3,1,3,259.83,0,1,0,0,0
000229ec398224ef6ca0657da4fc703e,1,5,216.87,0,1,0,0,0
00024acbcdf0a6daa1e931b038114c75,1,2,25.78,0,1,0,0,0
00042b26cf59d7ce69dfabb4e55b4fd9,1,3,218.04,0,1,0,0,0
...,...,...,...,...,...,...,...,...
fffc94f6ce00a00581880bf54a75a037,1,1,343.40,1,0,0,0,0
fffcd46ef2263f404302a634eb57f7eb,1,1,386.53,1,0,0,0,0
fffce4705a9662cd70adb13d4a31832d,1,3,116.85,0,1,0,0,0
fffe18544ffabc95dfada21779c9644f,1,3,64.71,0,1,0,0,0
fffe41c64501cc87c801fd61db3f6244,1,1,55.79,0,1,0,0,0

### Traitement Order_reviews

In [183]:
df_order_reviews.head()

,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
review_id,,,,,,
7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18,2018-01-18 21:46:59
80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10,2018-03-11 03:05:13
228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17,2018-02-18 14:36:24
e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21,2017-04-21 22:02:06
f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01,2018-03-02 10:26:53

In [184]:
df_order_reviews['order_id'].duplicated().value_counts()

order_id
False    98673
True       551
Name: count, dtype: int64

Traitement nécéssaire pour aggreger Order_reviews dans Orders:
1. Supprimer les comment title et message
2. Grouper par order_id

In [185]:
agg = {
    'review_score': ['min', 'max', 'mean'],
    'review_creation_date': ['min', 'max', 'mean'],
    'review_answer_timestamp': ['min', 'max', 'mean']
}
df_order_reviews = df_order_reviews.drop(columns=['review_comment_title', 'review_comment_message'])
df_order_reviews = df_order_reviews.groupby('order_id').agg(agg)
df_order_reviews.columns = df_order_reviews.columns.get_level_values(0) + '_' + df_order_reviews.columns.get_level_values(1)
df_order_reviews

,review_score_min,review_score_max,review_score_mean,review_creation_date_min,review_creation_date_max,review_creation_date_mean,review_answer_timestamp_min,review_answer_timestamp_max,review_answer_timestamp_mean
order_id,,,,,,,,,
00010242fe8c5a6d1ba2dd792cb16214,5,5,5.0,2017-09-21,2017-09-21,2017-09-21,2017-09-22 10:57:03,2017-09-22 10:57:03,2017-09-22 10:57:03
00018f77f2f0320c557190d7a144bdd3,4,4,4.0,2017-05-13,2017-05-13,2017-05-13,2017-05-15 11:34:13,2017-05-15 11:34:13,2017-05-15 11:34:13
000229ec398224ef6ca0657da4fc703e,5,5,5.0,2018-01-23,2018-01-23,2018-01-23,2018-01-23 16:06:31,2018-01-23 16:06:31,2018-01-23 16:06:31
00024acbcdf0a6daa1e931b038114c75,4,4,4.0,2018-08-15,2018-08-15,2018-08-15,2018-08-15 16:39:01,2018-08-15 16:39:01,2018-08-15 16:39:01
00042b26cf59d7ce69dfabb4e55b4fd9,5,5,5.0,2017-03-02,2017-03-02,2017-03-02,2017-03-03 10:54:59,2017-03-03 10:54:59,2017-03-03 10:54:59
...,...,...,...,...,...,...,...,...,...
fffc94f6ce00a00581880bf54a75a037,5,5,5.0,2018-05-11,2018-05-11,2018-05-11,2018-05-14 12:53:47,2018-05-14 12:53:47,2018-05-14 12:53:47
fffcd46ef2263f404302a634eb57f7eb,5,5,5.0,2018-07-24,2018-07-24,2018-07-24,2018-07-25 09:25:29,2018-07-25 09:25:29,2018-07-25 09:25:29
fffce4705a9662cd70adb13d4a31832d,5,5,5.0,2017-10-29,2017-10-29,2017-10-29,2017-10-29 21:33:52,2017-10-29 21:33:52,2017-10-29 21:33:52
fffe18544ffabc95dfada21779c9644f,5,5,5.0,2017-08-17,2017-08-17,2017-08-17,2017-08-18 12:24:05,2017-08-18 12:24:05,2017-08-18 12:24:05
fffe41c64501cc87c801fd61db3f6244,5,5,5.0,2018-06-15,2018-06-15,2018-06-15,2018-06-17 21:27:09,2018-06-17 21:27:09,2018-06-17 21:27:09

### Aggregation

In [186]:
df_orders = df_orders.join(df_customers, on='customer_id', how='left')
df_orders = df_orders.join(df_order_payments, on='order_id', how='left')
df_orders = df_orders.join(df_order_reviews, on='order_id', how='left')
df_orders

,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,...,payment_type_voucher,review_score_min,review_score_max,review_score_mean,review_creation_date_min,review_creation_date_max,review_creation_date_mean,review_answer_timestamp_min,review_answer_timestamp_max,review_answer_timestamp_mean
order_id,,,,,,,,,,,,,,,,,,,,,
e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,...,1.0,4.0,4.0,4.0,2017-10-11,2017-10-11,2017-10-11,2017-10-12 03:43:48,2017-10-12 03:43:48,2017-10-12 03:43:48
53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,barreiras,...,0.0,4.0,4.0,4.0,2018-08-08,2018-08-08,2018-08-08,2018-08-08 18:37:50,2018-08-08 18:37:50,2018-08-08 18:37:50
47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,...,0.0,5.0,5.0,5.0,2018-08-18,2018-08-18,2018-08-18,2018-08-22 19:07:58,2018-08-22 19:07:58,2018-08-22 19:07:58
949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,...,0.0,5.0,5.0,5.0,2017-12-03,2017-12-03,2017-12-03,2017-12-05 19:21:58,2017-12-05 19:21:58,2017-12-05 19:21:58
ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,...,0.0,5.0,5.0,5.0,2018-02-17,2018-02-17,2018-02-17,2018-02-18 13:02:51,2018-02-18 13:02:51,2018-02-18 13:02:51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,6359f309b166b0196dbf7ad2ac62bb5a,12209,sao jose dos campos,...,0.0,5.0,5.0,5.0,2017-03-22,2017-03-22,2017-03-22,2017-03-23 11:02:08,2017-03-23 11:02:08,2017-03-23 11:02:08
63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,da62f9e57a76d978d02ab5362c509660,11722,praia grande,...,0.0,4.0,4.0,4.0,2018-03-01,2018-03-01,2018-03-01,2018-03-02 17:50:01,2018-03-02 17:50:01,2018-03-02 17:50:01
83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,737520a9aad80b3fbbdad19b66b37b30,45920,nova vicosa,...,0.0,5.0,5.0,5.0,2017-09-22,2017-09-22,2017-09-22,2017-09-22 23:10:57,2017-09-22 23:10:57,2017-09-22 23:10:57
11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,5097a5312c8b157bb7be58ae360ef43c,28685,japuiba,...,0.0,2.0,2.0,2.0,2018-01-26,2018-01-26,2018-01-26,2018-01-27 09:16:56,2018-01-27 09:16:56,2018-01-27 09:16:56
66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,60350aa974b26ff12caad89e55993bd6,83750,lapa,...,0.0,5.0,5.0,5.0,2018-03-17,2018-03-17,2018-03-17,2018-03-17 16:33:31,2018-03-17 16:33:31,2018-03-17 16:33:31

## Aggrégation de Orders, Products, Sellers dans Orders_items

### Traitement Sellers

In [187]:
df_sellers.head()

,seller_zip_code_prefix,seller_city,seller_state,seller_geolocation_lat,seller_geolocation_lng
seller_id,,,,,
3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP,-22.894561,-47.062380
d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP,-22.382440,-46.947605
ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ,-22.909624,-43.176774
c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP,-23.657453,-46.612406
51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP,-22.964436,-46.535090

In [188]:
df_sellers.index.has_duplicates

False

Pas de traitement nécéssaire de Sellers avant aggrégation dans Order_items

### Traitement Products

In [189]:
df_products.head()

,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
product_id,,,,,,,,
1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [190]:
df_products.index.has_duplicates

False

Pas de traitement nécéssaire de Products avant aggrégation dans Order_items

### Traitement de Orders

In [191]:
df_orders.head()

,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,...,payment_type_voucher,review_score_min,review_score_max,review_score_mean,review_creation_date_min,review_creation_date_max,review_creation_date_mean,review_answer_timestamp_min,review_answer_timestamp_max,review_answer_timestamp_mean
order_id,,,,,,,,,,,,,,,,,,,,,
e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,...,1.0,4.0,4.0,4.0,2017-10-11,2017-10-11,2017-10-11,2017-10-12 03:43:48,2017-10-12 03:43:48,2017-10-12 03:43:48
53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,barreiras,...,0.0,4.0,4.0,4.0,2018-08-08,2018-08-08,2018-08-08,2018-08-08 18:37:50,2018-08-08 18:37:50,2018-08-08 18:37:50
47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,...,0.0,5.0,5.0,5.0,2018-08-18,2018-08-18,2018-08-18,2018-08-22 19:07:58,2018-08-22 19:07:58,2018-08-22 19:07:58
949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,...,0.0,5.0,5.0,5.0,2017-12-03,2017-12-03,2017-12-03,2017-12-05 19:21:58,2017-12-05 19:21:58,2017-12-05 19:21:58
ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,...,0.0,5.0,5.0,5.0,2018-02-17,2018-02-17,2018-02-17,2018-02-18 13:02:51,2018-02-18 13:02:51,2018-02-18 13:02:51

In [192]:
df_orders.index.has_duplicates

False

Pas de traitement nécéssaire de Orders avant aggrégation dans Order_items

### Aggregation

In [193]:
df_order_items = df_order_items.join(df_orders, on='order_id', how='left')
df_order_items = df_order_items.join(df_sellers, on='seller_id', how='left')
df_order_items = df_order_items.join(df_products, on='product_id', how='left')

df_order_items

,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,customer_id,order_status,order_purchase_timestamp,order_approved_at,...,seller_geolocation_lat,seller_geolocation_lng,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
order_id,,,,,,,,,,,,,,,,,,,,,
00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,...,-22.498419,-44.125272,cool_stuff,58.0,598.0,4.0,650.0,28.0,9.0,14.0
00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,...,-23.564289,-46.519045,pet_shop,56.0,239.0,2.0,30000.0,50.0,30.0,40.0
000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,...,-22.271648,-46.165556,moveis_decoracao,59.0,695.0,2.0,3050.0,33.0,13.0,33.0
00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,2018-08-08 10:10:18,...,-20.554951,-47.387691,perfumaria,42.0,480.0,1.0,200.0,16.0,10.0,15.0
00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,...,-22.930408,-53.136438,ferramentas_jardim,59.0,409.0,1.0,3750.0,35.0,40.0,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,b51593916b4b8e0d6f66f2ae24f2673d,delivered,2018-04-23 13:57:06,2018-04-25 04:11:01,...,-26.912616,-48.674015,utilidades_domesticas,43.0,1002.0,3.0,10150.0,89.0,15.0,40.0
fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,84c5d4fbaf120aae381fad077416eaa0,delivered,2018-07-14 10:26:46,2018-07-17 04:31:48,...,-23.536609,-46.642445,informatica_acessorios,31.0,232.0,1.0,8950.0,45.0,26.0,38.0
fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,29309aa813182aaddc9b259e31b870e6,delivered,2017-10-23 17:07:56,2017-10-24 17:14:25,...,-25.469632,-49.291261,esporte_lazer,43.0,869.0,1.0,967.0,21.0,24.0,19.0
fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,b5e6afd5a41800fdf401e0272ca74655,delivered,2017-08-14 23:02:59,2017-08-15 00:04:32,...,-23.636321,-46.694586,informatica_acessorios,56.0,1306.0,1.0,100.0,20.0,20.0,20.0
fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,96d649da0cc4ff33bb408b199d4c7dcf,delivered,2018-06-09 17:00:18,2018-06-09 17:10:13,...,-21.757690,-48.829768,cama_mesa_banho,47.0,511.0,1.0,600.0,30.0,3.0,19.0

# Exploration

In [194]:
DF_MAIN = df_order_items.copy()

## Types des colonnes

In [195]:
DF_MAIN.dtypes

order_item_id                             int64
product_id                               object
seller_id                                object
shipping_limit_date              datetime64[ns]
price                                   float64
freight_value                           float64
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
customer_unique_id                       object
customer_zip_code_prefix                  int64
customer_city                            object
customer_state                           object
customer_geolocation_lat                float64
customer_geolocation_lng                float64
payment_sequential                      float64
payment_installments                    float64
payment_value                           float64
payment_type_boleto                     float64
payment_type_credit_card                float64
payment_type_debit_card                 float64
payment_type_not_defined                float64
payment_type_voucher                    float64
review_score_min                        float64
review_score_max                        float64
review_score_mean                       float64
review_creation_date_min         datetime64[ns]
review_creation_date_max         datetime64[ns]
review_creation_date_mean        datetime64[ns]
review_answer_timestamp_min      datetime64[ns]
review_answer_timestamp_max      datetime64[ns]
review_answer_timestamp_mean     datetime64[ns]
seller_zip_code_prefix                    int64
seller_city                              object
seller_state                             object
seller_geolocation_lat                  float64
seller_geolocation_lng                  float64
product_category_name                    object
product_name_lenght                     float64
product_description_lenght              float64
product_photos_qty                      float64
product_weight_g                        float64
product_length_cm                       float64
product_height_cm                       float64
product_width_cm                        float64
dtype: object

In [196]:
DF_MAIN.dtypes[DF_MAIN.dtypes == 'object']

product_id               object
seller_id                object
customer_id              object
order_status             object
customer_unique_id       object
customer_city            object
customer_state           object
seller_city              object
seller_state             object
product_category_name    object
dtype: object

In [197]:
DF_MAIN.drop(columns=['product_id', 'seller_id', 'customer_id', 'customer_unique_id'], inplace=True)

In [198]:
DF_MAIN.dtypes[DF_MAIN.dtypes == 'object']

order_status             object
customer_city            object
customer_state           object
seller_city              object
seller_state             object
product_category_name    object
dtype: object

In [213]:
for cat in DF_MAIN.dtypes[DF_MAIN.dtypes == 'object'].index:
    print(f'{cat:.<30}: {len(DF_MAIN[cat].unique()):>4} valeurs uniques')

order_status..................:    7 valeurs uniques
customer_city.................: 4110 valeurs uniques
customer_state................:   27 valeurs uniques
seller_city...................:  611 valeurs uniques
seller_state..................:   23 valeurs uniques
product_category_name.........:   74 valeurs uniques

In [136]:
label_encoders = {}
for cat in DF_MAIN.dtypes[DF_MAIN.dtypes == 'object'].index:
    label_encoders[cat] = preprocessing.LabelEncoder()
    DF_MAIN[cat] = label_encoders[cat].fit_transform(DF_MAIN[cat])
    
DF_MAIN.dtypes

order_item_id                             int64
shipping_limit_date              datetime64[ns]
price                                   float64
freight_value                           float64
order_status                              int32
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
customer_zip_code_prefix                  int64
customer_city                             int32
customer_state                            int32
customer_geolocation_lat                float64
customer_geolocation_lng                float64
payment_sequential                      float64
payment_installments                    float64
payment_value                           float64
payment_type_boleto                     float64
payment_type_credit_card                float64
payment_type_debit_card                 float64
payment_type_not_defined                float64
payment_type_voucher                    float64
review_score_min                        float64
review_score_max                        float64
review_score_mean                       float64
review_creation_date_min         datetime64[ns]
review_creation_date_max         datetime64[ns]
review_creation_date_mean        datetime64[ns]
review_answer_timestamp_min      datetime64[ns]
review_answer_timestamp_max      datetime64[ns]
review_answer_timestamp_mean     datetime64[ns]
seller_zip_code_prefix                    int64
seller_city                               int32
seller_state                              int32
seller_geolocation_lat                  float64
seller_geolocation_lng                  float64
product_category_name                     int32
product_name_lenght                     float64
product_description_lenght              float64
product_photos_qty                      float64
product_weight_g                        float64
product_length_cm                       float64
product_height_cm                       float64
product_width_cm                        float64
dtype: object

In [137]:
DF_MAIN.head()

,order_item_id,shipping_limit_date,price,freight_value,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,...,seller_geolocation_lat,seller_geolocation_lng,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
order_id,,,,,,,,,,,,,,,,,,,,,
00010242fe8c5a6d1ba2dd792cb16214,1,2017-09-19 09:45:35,58.90,13.29,2,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29,...,-22.498419,-44.125272,26,58.0,598.0,4.0,650.0,28.0,9.0,14.0
00018f77f2f0320c557190d7a144bdd3,1,2017-05-03 11:05:13,239.90,19.93,2,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15,...,-23.564289,-46.519045,63,56.0,239.0,2.0,30000.0,50.0,30.0,40.0
000229ec398224ef6ca0657da4fc703e,1,2018-01-18 14:48:30,199.00,17.87,2,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05,...,-22.271648,-46.165556,54,59.0,695.0,2.0,3050.0,33.0,13.0,33.0
00024acbcdf0a6daa1e931b038114c75,1,2018-08-15 10:10:18,12.99,12.79,2,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20,...,-20.554951,-47.387691,62,42.0,480.0,1.0,200.0,16.0,10.0,15.0
00042b26cf59d7ce69dfabb4e55b4fd9,1,2017-02-13 13:57:51,199.90,18.14,2,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17,...,-22.930408,-53.136438,40,59.0,409.0,1.0,3750.0,35.0,40.0,30.0